import{jsx as _jsx}from"react/jsx-runtime";/**
 * PS2 Effect - Framer Override
 * Delay: 4500ms → Duration: 0.5s
 * Settings từ control panel
 */export function PS2Effect(){return{variants:{hidden:{opacity:0,filter:"blur(50px)"},visible:{opacity:1,filter:"blur(0px)"}},initial:"hidden",animate:"visible",transition:{delay:4,duration:.5,ease:[.5,0,.1,1]},style:{textShadow:"0 0 10px rgba(100, 150, 255, 0.8), 0 0 20px rgba(100, 150, 255, 0.6), 0 0 40px rgba(100, 150, 255, 0.4), 0 0 60px rgba(100, 150, 255, 0.2)"}};}// Version với custom parameters
export function PS2EffectCustom(initialDelay=4.3,duration=.5,startBlur=50,endBlur=0,startOpacity=0,endOpacity=1,bloomIntensity=1,easingX1=.5,easingY1=0,easingX2=.1,easingY2=1// Bezier Y2
){// Tính glow shadows dựa trên bloom intensity
const glowShadows=bloomIntensity>0?`0 0 ${10*bloomIntensity}px rgba(100, 150, 255, ${.8*bloomIntensity}), 0 0 ${20*bloomIntensity}px rgba(100, 150, 255, ${.6*bloomIntensity}), 0 0 ${40*bloomIntensity}px rgba(100, 150, 255, ${.4*bloomIntensity}), 0 0 ${60*bloomIntensity}px rgba(100, 150, 255, ${.2*bloomIntensity})`:"none";return{variants:{hidden:{opacity:startOpacity,filter:`blur(${startBlur}px)`},visible:{opacity:endOpacity,filter:`blur(${endBlur}px)`}},initial:"hidden",animate:"visible",transition:{delay:initialDelay,duration:duration,ease:[easingX1,easingY1,easingX2,easingY2]},style:{textShadow:glowShadows}};}// Quick presets
export function PS2EffectQuick(){return PS2EffectCustom(4.5,.5,50,0,0,1,1,.5,0,.1,1);}export function PS2EffectNoDelay(){return PS2EffectCustom(0,.5,50,0,0,1,1,.5,0,.1,1);}export function PS2EffectSlow(){return PS2EffectCustom(4.5,2,60,0,0,1,1,.5,0,.1,1);}import{useContext as __legacyOverrideHOC_useContext}from"react";import{DataObserverContext as __legacyOverrideHOC_DataObserverContext}from"framer";export function withPS2Effect(C){return props=>{__legacyOverrideHOC_useContext(__legacyOverrideHOC_DataObserverContext);return _jsx(C,{...props,...PS2Effect(props)});};}withPS2Effect.displayName="PS2Effect";export function withPS2EffectCustom(C){return props=>{__legacyOverrideHOC_useContext(__legacyOverrideHOC_DataObserverContext);return _jsx(C,{...props,...PS2EffectCustom(props)});};}withPS2EffectCustom.displayName="PS2EffectCustom";export function withPS2EffectQuick(C){return props=>{__legacyOverrideHOC_useContext(__legacyOverrideHOC_DataObserverContext);return _jsx(C,{...props,...PS2EffectQuick(props)});};}withPS2EffectQuick.displayName="PS2EffectQuick";export function withPS2EffectNoDelay(C){return props=>{__legacyOverrideHOC_useContext(__legacyOverrideHOC_DataObserverContext);return _jsx(C,{...props,...PS2EffectNoDelay(props)});};}withPS2EffectNoDelay.displayName="PS2EffectNoDelay";export function withPS2EffectSlow(C){return props=>{__legacyOverrideHOC_useContext(__legacyOverrideHOC_DataObserverContext);return _jsx(C,{...props,...PS2EffectSlow(props)});};}withPS2EffectSlow.displayName="PS2EffectSlow";
export const __FramerMetadata__ = {"exports":{"withPS2EffectSlow":{"type":"reactHoc","name":"withPS2EffectSlow","annotations":{"framerContractVersion":"1"}},"PS2EffectCustom":{"type":"override","name":"PS2EffectCustom","annotations":{"framerContractVersion":"1"}},"withPS2EffectCustom":{"type":"reactHoc","name":"withPS2EffectCustom","annotations":{"framerContractVersion":"1"}},"PS2EffectNoDelay":{"type":"override","name":"PS2EffectNoDelay","annotations":{"framerContractVersion":"1"}},"PS2EffectQuick":{"type":"override","name":"PS2EffectQuick","annotations":{"framerContractVersion":"1"}},"withPS2EffectNoDelay":{"type":"reactHoc","name":"withPS2EffectNoDelay","annotations":{"framerContractVersion":"1"}},"withPS2EffectQuick":{"type":"reactHoc","name":"withPS2EffectQuick","annotations":{"framerContractVersion":"1"}},"PS2Effect":{"type":"override","name":"PS2Effect","annotations":{"framerContractVersion":"1"}},"PS2EffectSlow":{"type":"override","name":"PS2EffectSlow","annotations":{"framerContractVersion":"1"}},"withPS2Effect":{"type":"reactHoc","name":"withPS2Effect","annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./FakePS2.map