// Generated by Framer (8e1ebfe)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  Link,
  SVG,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = { EdifFkLSq: { pressed: true } };
const cycleOrder = ["EdifFkLSq", "pmd1sdyr3"];
const serializationHash = "framer-eQRkb";
const variantClassNames = {
  EdifFkLSq: "framer-v-8o4p4e",
  pmd1sdyr3: "framer-v-1yugoh9",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Variant 1": "EdifFkLSq",
  "Variant 2": "pmd1sdyr3",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "EdifFkLSq",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "EdifFkLSq",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnter1agxxsx = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    setVariant("pmd1sdyr3");
  });
  const onMouseLeavetnkoqf = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: false });
    setVariant("EdifFkLSq");
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: "https://www.youtube.com/",
          motionChild: true,
          nodeId: "EdifFkLSq",
          openInNewTab: true,
          scopeId: "w_y0UFRQ5",
          children: /*#__PURE__*/ _jsx(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-8o4p4e",
              className,
              classNames
            )} framer-15i6ptr`,
            "data-framer-name": "Variant 1",
            "data-highlight": true,
            layoutDependency: layoutDependency,
            layoutId: "EdifFkLSq",
            onMouseEnter: onMouseEnter1agxxsx,
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              {
                "EdifFkLSq-pressed": { "data-framer-name": undefined },
                pmd1sdyr3: {
                  "data-framer-name": "Variant 2",
                  onMouseLeave: onMouseLeavetnkoqf,
                },
              },
              baseVariant,
              gestureVariant
            ),
            children: /*#__PURE__*/ _jsx(SVG, {
              className: "framer-exnd4z",
              "data-framer-name": "icon",
              layout: "position",
              layoutDependency: layoutDependency,
              layoutId: "fObHlxGI0",
              opacity: 1,
              svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 29 20"><path d="M 26.101 1.464 L 27.39 1.464 L 27.39 2.753 L 28.678 2.753 L 28.678 16.93 L 27.39 16.93 L 27.39 18.219 L 26.101 18.219 L 26.101 19.508 L 2.901 19.508 L 2.901 18.219 L 1.612 18.219 L 1.612 16.93 L 0.323 16.93 L 0.323 2.753 L 1.612 2.753 L 1.612 1.464 L 2.901 1.464 L 2.901 0.175 L 26.101 0.175 Z M 10.634 14.353 L 13.212 14.353 L 13.212 13.064 L 15.79 13.064 L 15.79 11.775 L 18.367 11.775 L 18.367 10.486 L 19.656 10.486 L 19.656 9.197 L 18.367 9.197 L 18.367 7.908 L 15.79 7.908 L 15.79 6.619 L 13.212 6.619 L 13.212 5.33 L 10.634 5.33 Z" fill="rgba(240,233,207,0.48)"></path></svg>',
              svgContentId: 11874026510,
              withExternalLayout: true,
              ...addPropertyOverrides(
                {
                  "EdifFkLSq-pressed": {
                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 29 20"><path d="M 26.101 1.464 L 27.39 1.464 L 27.39 2.753 L 28.678 2.753 L 28.678 16.93 L 27.39 16.93 L 27.39 18.219 L 26.101 18.219 L 26.101 19.508 L 2.901 19.508 L 2.901 18.219 L 1.612 18.219 L 1.612 16.93 L 0.323 16.93 L 0.323 2.753 L 1.612 2.753 L 1.612 1.464 L 2.901 1.464 L 2.901 0.175 L 26.101 0.175 Z M 10.634 14.353 L 13.212 14.353 L 13.212 13.064 L 15.79 13.064 L 15.79 11.775 L 18.367 11.775 L 18.367 10.486 L 19.656 10.486 L 19.656 9.197 L 18.367 9.197 L 18.367 7.908 L 15.79 7.908 L 15.79 6.619 L 13.212 6.619 L 13.212 5.33 L 10.634 5.33 Z" fill="var(--token-636575f0-2e74-4bb5-915b-172a2629f828, rgb(241, 195, 36)) /* {&quot;name&quot;:&quot;yellow-9&quot;} */"></path></svg>',
                    svgContentId: 11844216313,
                  },
                  pmd1sdyr3: {
                    svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 29 20"><path d="M 26.101 1.464 L 27.39 1.464 L 27.39 2.753 L 28.678 2.753 L 28.678 16.93 L 27.39 16.93 L 27.39 18.219 L 26.101 18.219 L 26.101 19.508 L 2.901 19.508 L 2.901 18.219 L 1.612 18.219 L 1.612 16.93 L 0.323 16.93 L 0.323 2.753 L 1.612 2.753 L 1.612 1.464 L 2.901 1.464 L 2.901 0.175 L 26.101 0.175 Z M 10.634 14.353 L 13.212 14.353 L 13.212 13.064 L 15.79 13.064 L 15.79 11.775 L 18.367 11.775 L 18.367 10.486 L 19.656 10.486 L 19.656 9.197 L 18.367 9.197 L 18.367 7.908 L 15.79 7.908 L 15.79 6.619 L 13.212 6.619 L 13.212 5.33 L 10.634 5.33 Z" fill="var(--token-636575f0-2e74-4bb5-915b-172a2629f828, rgb(241, 195, 36)) /* {&quot;name&quot;:&quot;yellow-9&quot;} */"></path></svg>',
                    svgContentId: 11844216313,
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-eQRkb.framer-15i6ptr, .framer-eQRkb .framer-15i6ptr { display: block; }",
  ".framer-eQRkb.framer-8o4p4e { cursor: pointer; gap: 0px; height: 41px; overflow: hidden; position: relative; text-decoration: none; width: 32px; }",
  ".framer-eQRkb .framer-exnd4z { flex: none; height: 20px; left: calc(50.00000000000002% - 29px / 2); position: absolute; top: calc(50.00000000000002% - 20px / 2); width: 29px; }",
  ".framer-eQRkb.framer-v-1yugoh9.framer-8o4p4e { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 41px); }",
  ".framer-eQRkb.framer-v-8o4p4e.pressed.framer-8o4p4e { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 41px); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 32
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"pmd1sdyr3":{"layout":["fixed","fixed"]},"oR2ISzL31":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerw_y0UFRQ5 = withCSS(Component, css, "framer-eQRkb");
export default Framerw_y0UFRQ5;
Framerw_y0UFRQ5.displayName = "M-youtube";
Framerw_y0UFRQ5.defaultProps = { height: 32, width: 32 };
addPropertyControls(Framerw_y0UFRQ5, {
  variant: {
    options: ["EdifFkLSq", "pmd1sdyr3"],
    optionTitles: ["Variant 1", "Variant 2"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(Framerw_y0UFRQ5, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerw_y0UFRQ5",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"pmd1sdyr3":{"layout":["fixed","fixed"]},"oR2ISzL31":{"layout":["fixed","fixed"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "32",
        framerIntrinsicHeight: "32",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./w_y0UFRQ5.map
