import{jsx as _jsx}from"react/jsx-runtime";import{addPropertyControls,ControlType,RenderTarget}from"framer";import{motion,useInView}from"framer-motion";import{useState,useEffect,useRef,useMemo}from"react";/**
 * @framerSupportedLayoutWidth auto
 * @framerSupportedLayoutHeight auto
 */export default function TextShadow(props){const{text,textPart2,color,colorPart2,font,shadowColor1,shadowColor2,master1=1,master2=2,caseSetting="none",offsetY=50,animationSpeed=.6,staggerDelay=.1,animationDelayDown=0,animationDelayUp=0,playOnce=true,style}=props;const[entryDirection,setEntryDirection]=useState("down");const containerRef=useRef(null);const isCanvas=RenderTarget.current()===RenderTarget.canvas;const isInView=useInView(containerRef,{once:playOnce});// Scroll direction detection
useEffect(()=>{if(isCanvas||!containerRef.current)return;const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){const rect=entry.boundingClientRect;const viewportHeight=window.innerHeight;if(rect.top<viewportHeight/2){setEntryDirection("up");}else{setEntryDirection("down");}}});},{threshold:0});observer.observe(containerRef.current);return()=>observer.disconnect();},[isCanvas,playOnce]);// Build text shadows
const s1=[`${shadowColor1} ${-master1}px ${-master1}px 0px`,`${shadowColor1} ${master1}px ${-master1}px 0px`,`${shadowColor1} ${-master1}px ${master1}px 0px`,`${shadowColor1} ${master1}px ${master1}px 0px`,`${shadowColor1} ${-master1}px 0px 0px`,`${shadowColor1} ${master1}px 0px 0px`,`${shadowColor1} 0px ${master1}px 0px`,`${shadowColor1} 0px ${-master1}px 0px`];const s2=[`${shadowColor2} 0px ${master2*2}px 0px`,`${shadowColor2} ${master2}px ${master2*2}px 0px`,`${shadowColor2} ${-master2}px ${master2*2}px 0px`];const textShadow=[...s1,...s2].join(", ");// Apply case transformation
const fullText=`${text}${textPart2}`;let displayText=fullText;if(caseSetting==="uppercase")displayText=fullText.toUpperCase();else if(caseSetting==="lowercase")displayText=fullText.toLowerCase();else if(caseSetting==="capitalize")displayText=fullText.replace(/\b\w/g,c=>c.toUpperCase());// Split into lines
const lines=useMemo(()=>{return displayText.split("\n");},[displayText]);const part1Length=text.length;// Function to render colored text for a line
const renderColoredText=(line,lineStartIndex)=>{return line.split("").map((char,charIndex)=>{const globalIndex=lineStartIndex+charIndex;const charColor=globalIndex<part1Length?color:colorPart2;return /*#__PURE__*/_jsx("span",{style:{color:charColor},children:char},charIndex);});};// Calculate animation values
const dynamicOffsetY=entryDirection==="down"?offsetY:-offsetY;const baseDelay=entryDirection==="down"?animationDelayDown:animationDelayUp;const textStyle={textShadow,...font,width:"100%",textAlign:font.textAlign};let currentCharIndex=0;return /*#__PURE__*/_jsx(motion.div,{ref:containerRef,style:{...style,display:"flex",flexDirection:"column",alignItems:font.textAlign==="center"?"center":font.textAlign==="right"?"flex-end":"flex-start"},children:lines.map((line,index)=>{const lineStartIndex=currentCharIndex;currentCharIndex+=line.length+1;const coloredContent=line.trim()===""?"\xa0":renderColoredText(line,lineStartIndex);// Reverse stagger order when entering from top
const staggerIndex=entryDirection==="down"?index:lines.length-1-index;return /*#__PURE__*/_jsx(motion.div,{initial:isCanvas?{opacity:1,y:0}:{opacity:0,y:dynamicOffsetY},animate:isCanvas?{opacity:1,y:0}:isInView?{opacity:1,y:0}:{opacity:0,y:dynamicOffsetY},transition:{duration:animationSpeed,delay:baseDelay+staggerIndex*staggerDelay,ease:"easeOut"},style:textStyle,children:coloredContent},`${index}-${isInView}`);})});}TextShadow.defaultProps={text:"Text Shadow",textPart2:"",color:"#fff",colorPart2:"#4ECDC4",font:{fontSize:"40px",fontWeight:"700",letterSpacing:"-0.04em",lineHeight:"1em"},shadowColor1:"rgb(73, 59, 12)",shadowColor2:"rgb(40, 32, 1)",master1:1,master2:2,caseSetting:"none",animationSpeed:.6,offsetY:50,staggerDelay:.1,animationDelayDown:0,animationDelayUp:0,playOnce:true};addPropertyControls(TextShadow,{text:{type:ControlType.String,title:"Text Part 1",defaultValue:"Text Shadow",displayTextArea:true},textPart2:{type:ControlType.String,title:"Text Part 2",defaultValue:"",displayTextArea:true},color:{type:ControlType.Color,title:"Color Part 1",defaultValue:"#fff"},colorPart2:{type:ControlType.Color,title:"Color Part 2",defaultValue:"#4ECDC4"},font:{type:ControlType.Font,title:"Font",controls:"extended"},shadowColor1:{type:ControlType.Color,title:"Border Color",defaultValue:"rgb(73, 59, 12)"},shadowColor2:{type:ControlType.Color,title:"Shadow Color",defaultValue:"rgb(40, 32, 1)"},master1:{type:ControlType.Number,title:"Border Width",defaultValue:1,min:0,max:10,step:.5},master2:{type:ControlType.Number,title:"Shadow Depth",defaultValue:2,min:0,max:10,step:.5},caseSetting:{type:ControlType.Enum,title:"Text Case",options:["none","uppercase","lowercase","capitalize"],optionTitles:["None","UPPERCASE","lowercase","Capitalize"],defaultValue:"none"},animationSpeed:{type:ControlType.Number,title:"Animation Speed",defaultValue:.6,min:.1,max:2,step:.1,unit:"s"},offsetY:{type:ControlType.Number,title:"Y Offset",defaultValue:50,min:0,max:200,step:5,unit:"px"},staggerDelay:{type:ControlType.Number,title:"Stagger Delay",defaultValue:.1,min:0,max:.5,step:.05,unit:"s"},animationDelayDown:{type:ControlType.Number,title:"Delay (Scroll Up)",defaultValue:0,min:0,max:3,step:.1,unit:"s"},animationDelayUp:{type:ControlType.Number,title:"Delay (Scroll Down)",defaultValue:0,min:0,max:3,step:.1,unit:"s"},playOnce:{type:ControlType.Boolean,title:"Play Once",defaultValue:true,enabledTitle:"Once",disabledTitle:"Repeat"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"TextShadow","slots":[],"annotations":{"framerSupportedLayoutHeight":"auto","framerSupportedLayoutWidth":"auto","framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Custome_Text_Shadow.map