import{jsx as _jsx}from"react/jsx-runtime";import{addPropertyControls,ControlType,RenderTarget}from"framer";import{motion,useInView}from"framer-motion";import{useMemo,useRef,useState,useEffect}from"react";/**
 * @framerDisableUnlink
 * @framerSupportedLayoutWidth auto
 * @framerSupportedLayoutHeight auto
 */export default function SimpleAnimatedText(props){const{text,textColor,font,animationSpeed,offsetY,staggerDelay,animationDelayUp,animationDelayDown,playOnce,style}=props;const lines=useMemo(()=>{return text.split("\n");},[text]);const containerRef=useRef(null);const isInView=useInView(containerRef,{once:playOnce});// Detect if we're in canvas (editor) or preview/published
const isCanvas=RenderTarget.current()===RenderTarget.canvas;// Track which direction element enters viewport from
const[entryDirection,setEntryDirection]=useState("down");useEffect(()=>{if(isCanvas||!containerRef.current)return;const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){const rect=entry.boundingClientRect;const viewportHeight=window.innerHeight;if(rect.top<viewportHeight/2){setEntryDirection("up");}else{setEntryDirection("down");}}});},{threshold:0});observer.observe(containerRef.current);return()=>observer.disconnect();},[isCanvas,playOnce]);// Calculate offset based on entry direction
const dynamicOffsetY=entryDirection==="down"?offsetY:-offsetY;// Use appropriate delay based on scroll direction
const animationDelay=entryDirection==="down"?animationDelayUp:animationDelayDown;let currentCharIndex=0;return /*#__PURE__*/_jsx(motion.div,{ref:containerRef,style:{...style,display:"flex",flexDirection:"column",alignItems:font.textAlign==="center"?"center":font.textAlign==="right"?"flex-end":"flex-start"},children:lines.map((line,index)=>{currentCharIndex+=line.length+1;// Reverse stagger order when entering from top
const staggerIndex=entryDirection==="down"?index:lines.length-1-index;// Use different delay based on entry direction
const baseDelay=entryDirection==="down"?animationDelayDown:animationDelayUp;return /*#__PURE__*/_jsx(motion.div,{initial:isCanvas?{opacity:1,y:0}:{opacity:0,y:dynamicOffsetY},animate:isCanvas?{opacity:1,y:0}:isInView?{opacity:1,y:0}:{opacity:0,y:dynamicOffsetY},transition:{duration:animationSpeed,delay:baseDelay+staggerIndex*staggerDelay,ease:"easeOut"},style:{...font,color:textColor,width:"100%",textAlign:font.textAlign},children:line.trim()===""?"\xa0":line},`${index}-${isInView}`);})});}SimpleAnimatedText.defaultProps={text:"Simple Animated\nText Component",textColor:"#000000",font:{fontFamily:"Inter",fontSize:48,fontWeight:"700",lineHeight:"1.2em",letterSpacing:"-0.02em",textAlign:"left"},animationSpeed:.6,offsetY:50,staggerDelay:.1,animationDelayUp:0,animationDelayDown:0,playOnce:true};addPropertyControls(SimpleAnimatedText,{text:{type:ControlType.String,title:"Text",displayTextArea:true},textColor:{type:ControlType.Color,title:"Text Color"},font:{type:ControlType.Font,controls:"extended",title:"Typography"},animationSpeed:{type:ControlType.Number,title:"Animation Speed",min:.1,max:2,step:.1,unit:"s"},offsetY:{type:ControlType.Number,title:"Y Offset",min:0,max:200,step:5,unit:"px"},staggerDelay:{type:ControlType.Number,title:"Stagger Delay",min:0,max:.5,step:.05,unit:"s"},animationDelayUp:{type:ControlType.Number,title:"Delay (Scroll Up)",min:0,max:3,step:.1,unit:"s",defaultValue:0},animationDelayDown:{type:ControlType.Number,title:"Delay (Scroll Down)",min:0,max:3,step:.1,unit:"s",defaultValue:0},playOnce:{type:ControlType.Boolean,title:"Play Once",enabledTitle:"Once",disabledTitle:"Repeat",defaultValue:true}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"SimpleAnimatedText","slots":[],"annotations":{"framerContractVersion":"1","framerDisableUnlink":"* @framerSupportedLayoutWidth auto","framerSupportedLayoutHeight":"auto"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Sub_Title_Animation.map