// 9-slice CSS component for Framer
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{addPropertyControls,ControlType}from"framer";import{useMemo}from"react";/**
 * 9-Slice CSS Component
 *
 * @framerSupportedLayoutWidth any-prefer-fixed
 * @framerSupportedLayoutHeight any-prefer-fixed
 */export default function NineSlice(props){const{image={src:"/framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.svg",alt:"SVG 9-slice"},left=32,right=32,top=32,bottom=32,backgroundColor="#FFFFFF",svgColor="#000000",style,gradient="linear-gradient(135deg, #FFFFFF 0%, #EEEEEE 100%)",useGradient=false}=props;// border-image-slice expects numbers, not px
const borderSlice=`${top} ${right} ${bottom} ${left} fill`// Use all 4 sides for 9-slice
;const borderWidth=`${top}px ${right}px ${bottom}px ${left}px`;// If SVG, inject fill color if possible
const borderImageSource=useMemo(()=>{if(!image)return undefined;if(typeof image==="string"){// Assume SVG markup string
let svg=image;return`url('data:image/svg+xml,${encodeURIComponent(svg)}')`;}if(image.src&&image.src.endsWith(".svg")){try{if(typeof window==="undefined")return`url('${image.src}')`;if(image.src.startsWith("data:image/svg+xml")){let svg=decodeURIComponent(image.src.split(",")[1]);return`url('data:image/svg+xml,${encodeURIComponent(svg)}')`;}return`url('${image.src}')`;}catch{return`url('${image.src}')`;}}return`url('${image.src||image}')`;},[image]);const containerStyle={...style,position:"relative",width:"100%",height:"100%",backgroundColor:undefined,boxSizing:"border-box",borderStyle:"solid",borderWidth,borderImageSource,borderImageSlice:borderSlice,borderImageWidth:borderWidth,borderImageOutset:0,borderImageRepeat:"stretch",overflow:"hidden",imageRendering:"pixelated"};return /*#__PURE__*/_jsxs("div",{style:containerStyle,"aria-label":"SVG 9-slice",children:[/*#__PURE__*/_jsx("div",{style:{position:"absolute",top:0,left:0,right:0,bottom:0,width:"100%",height:"100%",background:useGradient?gradient:backgroundColor,zIndex:0}}),/*#__PURE__*/_jsx("div",{style:{position:"relative",zIndex:1,width:"fit-content",height:"fit-content",margin:"auto",padding:24,display:"flex",alignItems:props.alignment||"center",justifyContent:props.alignment||"center",boxSizing:"border-box",minWidth:0,minHeight:0,maxWidth:"100%",maxHeight:"100%"},children:props.children})]});}addPropertyControls(NineSlice,{image:{type:ControlType.String,title:"SVG Code",placeholder:"Paste SVG markup here…",defaultValue:`<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64' viewBox='0 0 64 64'><rect x='0' y='0' width='64' height='64' rx='16' fill='#000'/></svg>`,displayTextArea:true},left:{type:ControlType.Number,title:"Left",defaultValue:32,min:0,max:200,step:1,displayStepper:true},right:{type:ControlType.Number,title:"Right",defaultValue:32,min:0,max:200,step:1,displayStepper:true},top:{type:ControlType.Number,title:"Top",defaultValue:32,min:0,max:200,step:1,displayStepper:true},bottom:{type:ControlType.Number,title:"Bottom",defaultValue:32,min:0,max:200,step:1,displayStepper:true},useGradient:{type:ControlType.Boolean,title:"Use Gradient",defaultValue:false,enabledTitle:"Gradient",disabledTitle:"Solid"},backgroundColor:{type:ControlType.Color,title:"Color",defaultValue:"#FFFFFF",hidden:({useGradient})=>!!useGradient},gradient:{type:ControlType.String,title:"Gradient CSS",defaultValue:"linear-gradient(135deg, #FFFFFF 0%, #EEEEEE 100%)",placeholder:"CSS gradient value…",hidden:({useGradient})=>!useGradient},alignment:{type:ControlType.Enum,title:"Content Align",options:["flex-start","center","flex-end"],optionTitles:["Start","Center","End"],defaultValue:"center"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"NineSlice","slots":["children"],"annotations":{"framerContractVersion":"1","framerSupportedLayoutHeight":"any-prefer-fixed","framerSupportedLayoutWidth":"any-prefer-fixed"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./NineSlice.map