// SpriteAnimation animation component with customizable frame rate and playback controls
import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{useState,useEffect,useRef,startTransition}from"react";import{addPropertyControls,ControlType,useIsStaticRenderer}from"framer";/**
 * SpriteAnimation Animation Component
 * 
 * Animates through frames of a spritesheet image with customizable playback controls
 *
 * @framerIntrinsicWidth 100
 * @framerIntrinsicHeight 100
 *
 * @framerSupportedLayoutWidth fixed
 * @framerSupportedLayoutHeight fixed
 */export default function SpriteAnimation(props){const{spritesheet={src:"/framerusercontent.com/images/GfGkADagM4KEibNcIiRUWlfrR0.jpg",alt:"SpriteAnimation"},frameWidth=100,frameHeight=100,totalFrames=8,framesPerRow=4,frameRate=12,autoPlay=true,loop=true,playOnHover=false,backgroundColor="#FFFFFF",scale=1,positionX=0,positionY=0,showController=true,startFrame=0}=props;const[currentFrame,setCurrentFrame]=useState(startFrame);const[isPlaying,setIsPlaying]=useState(autoPlay&&!playOnHover);const[isHovered,setIsHovered]=useState(false);const intervalRef=useRef(null);const isStatic=useIsStaticRenderer();// Calculate frame position
const frameX=currentFrame%framesPerRow*frameWidth;const frameY=Math.floor(currentFrame/framesPerRow)*frameHeight;// Animation logic
useEffect(()=>{if(isStatic)return;const shouldPlay=playOnHover?isHovered:isPlaying;if(shouldPlay&&frameRate>0){intervalRef.current=window.setInterval(()=>{startTransition(()=>{setCurrentFrame(prev=>{const nextFrame=prev+1;if(nextFrame>=totalFrames){return loop?0:prev;}return nextFrame;});});},1e3/frameRate);}else{if(intervalRef.current){clearInterval(intervalRef.current);intervalRef.current=null;}}return()=>{if(intervalRef.current){clearInterval(intervalRef.current);}};},[isPlaying,isHovered,frameRate,totalFrames,loop,playOnHover,isStatic]);// Reset to starting frame when not playing and not on hover mode
useEffect(()=>{if(!playOnHover&&!isPlaying){startTransition(()=>setCurrentFrame(startFrame));}},[isPlaying,playOnHover,startFrame]);const handleMouseEnter=()=>{if(playOnHover){startTransition(()=>{setIsHovered(true);setCurrentFrame(startFrame);});}};const handleMouseLeave=()=>{if(playOnHover){startTransition(()=>{setIsHovered(false);setCurrentFrame(startFrame);});}};return /*#__PURE__*/_jsxs("div",{style:{width:"100%",height:"100%",backgroundColor,overflow:"hidden",position:"relative"},onMouseEnter:isStatic?undefined:handleMouseEnter,onMouseLeave:isStatic?undefined:handleMouseLeave,children:[/*#__PURE__*/_jsx("div",{style:{width:"100%",height:"100%",backgroundImage:`url(${spritesheet.src})`,backgroundPosition:`-${frameX}px -${frameY}px`,backgroundRepeat:"no-repeat",backgroundSize:`${framesPerRow*frameWidth}px auto`,imageRendering:"pixelated",transform:`scale(${scale}) translate(${positionX}px, ${positionY}px)`,transformOrigin:"top left"},role:"img","aria-label":spritesheet.alt}),!isStatic&&!playOnHover&&showController&&/*#__PURE__*/_jsxs("div",{style:{position:"absolute",bottom:8,right:8,backgroundColor:"rgba(0, 0, 0, 0.7)",color:"white",borderRadius:4,padding:"4px 8px",fontSize:12,fontFamily:"system-ui, sans-serif",pointerEvents:"none"},children:[isPlaying?"Playing":"Paused"," • Frame ",currentFrame+1,"/",totalFrames]})]});}addPropertyControls(SpriteAnimation,{spritesheet:{type:ControlType.ResponsiveImage,title:"SpriteAnimation Image"},frameWidth:{type:ControlType.Number,title:"Frame Width",defaultValue:100,min:1,max:1e3,step:1,unit:"px"},frameHeight:{type:ControlType.Number,title:"Frame Height",defaultValue:100,min:1,max:1e3,step:1,unit:"px"},totalFrames:{type:ControlType.Number,title:"Total Frames",defaultValue:8,min:1,max:1e3,step:1},framesPerRow:{type:ControlType.Number,title:"Frames Per Row",defaultValue:4,min:1,max:100,step:1},startFrame:{type:ControlType.Number,title:"Start Frame",defaultValue:0,min:0,max:999,step:1},frameRate:{type:ControlType.Number,title:"Frame Rate",defaultValue:12,min:1,max:60,step:1,unit:"fps"},autoPlay:{type:ControlType.Boolean,title:"Auto Play",defaultValue:true,enabledTitle:"On",disabledTitle:"Off",hidden:({playOnHover})=>playOnHover},loop:{type:ControlType.Boolean,title:"Loop",defaultValue:true,enabledTitle:"On",disabledTitle:"Off"},playOnHover:{type:ControlType.Boolean,title:"Play on Hover",defaultValue:false,enabledTitle:"On",disabledTitle:"Off"},backgroundColor:{type:ControlType.Color,title:"Background",defaultValue:"#FFFFFF"},scale:{type:ControlType.Number,title:"Scale",defaultValue:1,min:.1,max:5,step:.1},positionX:{type:ControlType.Number,title:"Position X",defaultValue:0,min:-500,max:500,step:1,unit:"px"},positionY:{type:ControlType.Number,title:"Position Y",defaultValue:0,min:-500,max:500,step:1,unit:"px"},showController:{type:ControlType.Boolean,title:"Show Controller",defaultValue:true,enabledTitle:"Show",disabledTitle:"Hide",hidden:({playOnHover})=>playOnHover}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"SpriteAnimation","slots":[],"annotations":{"framerSupportedLayoutWidth":"fixed","framerSupportedLayoutHeight":"fixed","framerIntrinsicHeight":"100","framerContractVersion":"1","framerIntrinsicWidth":"100"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./SpriteAnimation.map