// Generated by Framer (27b79d7)
export default function metadata(params, activeLocale) {
  return {
    description:
      "Mattles is a gamified trading platform where your on-chain activity directly powers your performance in a skill-based survival game",
    favicon:
      "/framerusercontent.com/assets/Xpj3ZvvYRk4fpyiLqs1TP7ccw2U.png",
    robots: "max-image-preview:large",
    socialImage:
      "/framerusercontent.com/assets/aM7h2PwLXhRzvQkqsxuctA1ovs.png",
    title: "A",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
