import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import*as React from"react";import{addPropertyControls,ControlType}from"framer";import{useCarouselState}from"/framerusercontent.com/modules/6hJuBDjZVWhS0E2W1Kft/BvHkP8FixhOrEys9fEQt/Store.js";/**
 * CarouselControl: wraps your designed button (children).
 * When clicked, it will control the carousel through the store.
 * Place this component around your button in the canvas.
 */export default function CarouselControl(props){const{direction,buttonMap,passthrough,width,height,children}=props;const[,setStore]=useCarouselState();const onClick=React.useCallback(()=>{setStore({direction,buttonMap});},[direction,buttonMap,setStore]);// If "passthrough" is enabled, clicks will go to the child directly (not blocked).
// Use passthrough = true when you want the child itself to handle clicks.
const style={width:"100%",height:"100%",display:"contents",...passthrough?{pointerEvents:"none"}:{cursor:"pointer"}};return /*#__PURE__*/_jsx("div",{style:style,onClick:passthrough?undefined:onClick,children:!passthrough?children:/*#__PURE__*/_jsxs("div",{style:{position:"relative",width:"100%",height:"100%"},children:[children,/*#__PURE__*/_jsx("div",{onClick:onClick,style:{position:"absolute",inset:0,// transparent overlay
background:"transparent",pointerEvents:"auto"}})]})});}CarouselControl.defaultProps={direction:"left",buttonMap:1,passthrough:false,width:48,height:48};addPropertyControls(CarouselControl,{direction:{type:ControlType.Enum,title:"Direction",options:["left","right"],optionTitles:["Left","Right"],defaultValue:"left"},buttonMap:{type:ControlType.Number,title:"Button Map",min:1,max:10,displayStepper:true,defaultValue:1},passthrough:{type:ControlType.Boolean,title:"Passthrough",defaultValue:false,description:"If enabled, clicks will pass through to the child. An invisible overlay will still catch the click and update the store."}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"CarouselControl","slots":["children"],"annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Carousel_Controller.map