import{jsx as _jsx,jsxs as _jsxs,Fragment as _Fragment}from"react/jsx-runtime";import{addPropertyControls,ControlType,RenderTarget}from"framer";import{motion,useInView}from"framer-motion";import{useRef,useMemo,useState,useEffect}from"react";/**
 * @framerDisableUnlink
 * @framerSupportedLayoutWidth auto
 * @framerSupportedLayoutHeight auto
 */export default function AnimatedText(props){const{textPart1,textPart2,colorPart1,colorPart2,font,animationSpeed,offsetY,staggerDelay,animationDelay,strokeWidth,blurAmount,glowBrightness,shadowHardX,shadowHardY,playOnce,style}=props;const containerRef=useRef(null);const isInView=useInView(containerRef,{once:playOnce});// Detect if we're in canvas (editor) or preview/published
const isCanvas=RenderTarget.current()===RenderTarget.canvas;// Track which direction element enters viewport from
const[entryDirection,setEntryDirection]=useState("down");useEffect(()=>{if(isCanvas||!containerRef.current)return;const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){// Check if element is entering from top or bottom
const rect=entry.boundingClientRect;const viewportHeight=window.innerHeight;if(rect.top<viewportHeight/2){// Element entering from top (scrolling down from above)
setEntryDirection("up");}else{// Element entering from bottom (scrolling up from below)
setEntryDirection("down");}}});},{threshold:0});observer.observe(containerRef.current);return()=>observer.disconnect();},[isCanvas,playOnce]);// Calculate offset based on entry direction
const dynamicOffsetY=entryDirection==="down"?offsetY:-offsetY;const lines=useMemo(()=>{const fullText=`${textPart1}${textPart2}`;return fullText.split("\n");},[textPart1,textPart2]);const part1Length=textPart1.length;// Layer 1: Fill shadows (exactly as specified)
const fillShadow=`
        0px 0px 16px rgba(244, 207, 67, 0.57),
        ${shadowHardX}px ${shadowHardY}px 0px #282001
    `.trim();// Layer 2: Stroke only (no fill)
const strokeStyle={WebkitTextStroke:`${strokeWidth}px #FFFFFF`,WebkitTextFillColor:"transparent",color:"transparent",backgroundColor:"transparent",paintOrder:"stroke"};const renderColoredText=(line,lineStartIndex)=>{const lineEndIndex=lineStartIndex+line.length;if(lineEndIndex<=part1Length){return /*#__PURE__*/_jsx("span",{style:{color:colorPart1},children:line});}if(lineStartIndex>=part1Length){return /*#__PURE__*/_jsx("span",{style:{color:colorPart2},children:line});}const splitPoint=part1Length-lineStartIndex;return /*#__PURE__*/_jsxs(_Fragment,{children:[/*#__PURE__*/_jsx("span",{style:{color:colorPart1},children:line.substring(0,splitPoint)}),/*#__PURE__*/_jsx("span",{style:{color:colorPart2},children:line.substring(splitPoint)})]});};let currentCharIndex=0;return /*#__PURE__*/_jsx(motion.div,{ref:containerRef,style:{...style,display:"flex",flexDirection:"column",alignItems:font.textAlign==="center"?"center":font.textAlign==="right"?"flex-end":"flex-start",overflow:"visible"},children:lines.map((line,index)=>{const lineStartIndex=currentCharIndex;currentCharIndex+=line.length+1;const coloredContent=line.trim()===""?"\xa0":renderColoredText(line,lineStartIndex);// Reverse stagger order when entering from top
const staggerIndex=entryDirection==="down"?index:lines.length-1-index;return /*#__PURE__*/_jsxs(motion.div,{initial:isCanvas?{opacity:1,y:0}:{opacity:0,y:dynamicOffsetY},animate:isCanvas?{opacity:1,y:0}:isInView?{opacity:1,y:0}:{opacity:0,y:dynamicOffsetY},transition:{duration:animationSpeed,delay:animationDelay+staggerIndex*staggerDelay,ease:"easeOut"},style:{width:"100%",textAlign:font.textAlign,position:"relative",minHeight:line.trim()===""?font.lineHeight:"auto"},children:[/*#__PURE__*/_jsx("div",{style:{...font,textShadow:fillShadow},children:coloredContent}),/*#__PURE__*/_jsx("div",{style:{position:"absolute",top:0,left:0,width:"100%",filter:`blur(${blurAmount}px) brightness(${glowBrightness})`,pointerEvents:"none"},"aria-hidden":"true",children:/*#__PURE__*/_jsx("div",{style:{...font,...strokeStyle,color:"transparent"},children:line.trim()===""?"\xa0":line})})]},`${index}-${entryDirection}-${isInView}`);})});}AnimatedText.defaultProps={textPart1:"Animated Text\nFirst Part",textPart2:"\nSecond Part",colorPart1:"#FF6B6B",colorPart2:"#4ECDC4",font:{fontFamily:"Inter",fontSize:48,fontWeight:"700",lineHeight:"1.2em",letterSpacing:"-0.02em",textAlign:"left"},animationSpeed:.6,offsetY:50,staggerDelay:.1,animationDelay:0,strokeWidth:1,blurAmount:4,glowBrightness:1,shadowHardX:0,shadowHardY:8,playOnce:true};addPropertyControls(AnimatedText,{textPart1:{type:ControlType.String,title:"Text Part 1",displayTextArea:true},textPart2:{type:ControlType.String,title:"Text Part 2",displayTextArea:true},colorPart1:{type:ControlType.Color,title:"Color Part 1"},colorPart2:{type:ControlType.Color,title:"Color Part 2"},font:{type:ControlType.Font,controls:"extended",title:"Typography"},animationSpeed:{type:ControlType.Number,title:"Animation Speed",min:.1,max:2,step:.1,unit:"s"},offsetY:{type:ControlType.Number,title:"Y Offset",min:0,max:200,step:5,unit:"px"},staggerDelay:{type:ControlType.Number,title:"Stagger Delay",min:0,max:.5,step:.05,unit:"s"},animationDelay:{type:ControlType.Number,title:"Animation Delay",min:0,max:3,step:.1,unit:"s",defaultValue:0},strokeWidth:{type:ControlType.Number,title:"Stroke Width",min:0,max:5,step:.5,unit:"px",defaultValue:1},blurAmount:{type:ControlType.Number,title:"Blur Amount",min:0,max:20,step:1,unit:"px",defaultValue:4},glowBrightness:{type:ControlType.Number,title:"Glow Brightness",min:1,max:3,step:.1,defaultValue:1},shadowHardX:{type:ControlType.Number,title:"Shadow Hard X",min:-50,max:50,step:1,unit:"px",defaultValue:0},shadowHardY:{type:ControlType.Number,title:"Shadow Hard Y",min:-50,max:50,step:1,unit:"px",defaultValue:8},playOnce:{type:ControlType.Boolean,title:"Play Once",enabledTitle:"Once",disabledTitle:"Repeat",defaultValue:true}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"AnimatedText","slots":[],"annotations":{"framerSupportedLayoutHeight":"auto","framerContractVersion":"1","framerDisableUnlink":"* @framerSupportedLayoutWidth auto"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Title_Animate.map