import{jsx as _jsx,jsxs as _jsxs}from"react/jsx-runtime";import{addPropertyControls,ControlType}from"framer";// --- helpers --------------------------------------------------------------
function extractFirstColor(svg,type,fallback){// Try style="... type: value ..."
const styleRe=new RegExp(`${type}\\s*:\\s*(#[0-9a-fA-F]{3,8}|[a-zA-Z]+|rgba?\\([^\\)]+\\)|currentColor)`,"i");const styleMatch=svg.match(styleRe);if(styleMatch&&styleMatch[1]&&!/none/i.test(styleMatch[1]))return styleMatch[1];// Try attribute type="value" (exclude fill-rule / stroke-line...)
const attrRe=new RegExp(`\\s${type}="(#[0-9a-fA-F]{3,8}|[a-zA-Z]+|rgba?\\([^"]+\\)|currentColor|none)"`,"i");const attrMatch=svg.match(attrRe);if(attrMatch&&attrMatch[1]&&!/none/i.test(attrMatch[1]))return attrMatch[1];return fallback;}function replaceAllFills(svg,newFill){let out=svg;// Replace style fills: fill: xxx;
out=out.replace(/fill\s*:\s*(#[0-9a-fA-F]{3,8}|[a-zA-Z]+|rgba?\([^;\)"]+\)|currentColor|none)/gi,`fill: ${newFill}`);// Replace attribute fills: fill="xxx"
out=out.replace(/(\s)fill="(#[0-9a-fA-F]{3,8}|[a-zA-Z]+|rgba?\([^"]+\)|currentColor|none)"/gi,`$1fill="${newFill}"`);// If no fill attribute anywhere, inject one on the first drawable element
if(!/\sfill="/i.test(out)){out=out.replace(/<((path|rect|circle|ellipse|polygon|polyline|g)\b[^>]*?)(\/?)>/i,(_m,attrs,_tag,selfClose)=>`<${attrs} fill="${newFill}"${selfClose||""}>`);}return out;}function replaceAllStrokes(svg,newStroke){let out=svg;// Replace style strokes: stroke: xxx;
out=out.replace(/stroke\s*:\s*(#[0-9a-fA-F]{3,8}|[a-zA-Z]+|rgba?\([^;\)"]+\)|currentColor|none)/gi,`stroke: ${newStroke}`);// Replace attribute strokes: stroke="xxx"
out=out.replace(/(\s)stroke="(#[0-9a-fA-F]{3,8}|[a-zA-Z]+|rgba?\([^"]+\)|currentColor|none)"/gi,`$1stroke="${newStroke}"`);// If no stroke attribute, inject on first drawable element (optional)
if(!/\sstroke="/i.test(out)){out=out.replace(/<((path|rect|circle|ellipse|polygon|polyline|g)\b[^>]*?)(\/?)>/i,(_m,attrs,_tag,selfClose)=>`<${attrs} stroke="${newStroke}"${selfClose||""}>`);}return out;}function applyColors(svg,fillColor,strokeColor){let updated=svg;if(fillColor)updated=replaceAllFills(updated,fillColor);if(strokeColor)updated=replaceAllStrokes(updated,strokeColor);return updated;}// --- component ------------------------------------------------------------
export default function Pixel_Background(props){const{svg,fillColor,strokeColor,left,right,top,bottom,useGradient,backgroundColor,gradient,children,hAlign,vAlign}=props;const effectiveFill=fillColor||extractFirstColor(svg,"fill","#000000");const effectiveStroke=strokeColor||extractFirstColor(svg,"stroke","#ffffff");const updatedSVG=applyColors(svg,effectiveFill,effectiveStroke);const encodedSVG=`url('data:image/svg+xml,${encodeURIComponent(updatedSVG)}')`;const borderSlice=`${top} ${right} ${bottom} ${left} fill`;const borderWidth=`${top}px ${right}px ${bottom}px ${left}px`;const justifyMap={Left:"flex-start",Center:"center",Right:"flex-end"};const alignMap={Top:"flex-start",Center:"center",Bottom:"flex-end"};return /*#__PURE__*/_jsxs("div",{style:{position:"relative",width:"100%",height:"100%",boxSizing:"border-box",borderStyle:"solid",borderWidth,borderImageSource:encodedSVG,borderImageSlice:borderSlice,borderImageWidth:borderWidth,borderImageOutset:0,borderImageRepeat:"stretch",overflow:"hidden",imageRendering:"pixelated"},children:[/*#__PURE__*/_jsx("div",{style:{position:"absolute",inset:0,background:useGradient?gradient:backgroundColor,zIndex:0}}),/*#__PURE__*/_jsx("div",{style:{position:"relative",zIndex:1,width:"100%",height:"100%",display:"flex",justifyContent:justifyMap[hAlign]||"center",alignItems:alignMap[vAlign]||"center",pointerEvents:"auto"},children:children})]});}Pixel_Background.defaultProps={svg:`<svg xmlns='http://www.w3.org/2000/svg' width='64' height='64' viewBox='0 0 64 64'>
<rect x='0' y='0' width='64' height='64' rx='16' fill='#000000' stroke='#ffffff' stroke-width='4'/>
</svg>`,fillColor:"#000000",strokeColor:"#ffffff",left:16,right:16,top:16,bottom:16,useGradient:false,backgroundColor:"#ffffff",gradient:"linear-gradient(135deg, #FFFFFF 0%, #EEEEEE 100%)",hAlign:"Center",vAlign:"Center"};addPropertyControls(Pixel_Background,{svg:{type:ControlType.String,title:"SVG Code",displayTextArea:true,placeholder:"Paste your SVG here…"},fillColor:{type:ControlType.Color,title:"Fill"},strokeColor:{type:ControlType.Color,title:"Stroke"},left:{type:ControlType.Number,title:"Left",min:0,max:200,defaultValue:16,displayStepper:true},right:{type:ControlType.Number,title:"Right",min:0,max:200,defaultValue:16,displayStepper:true},top:{type:ControlType.Number,title:"Top",min:0,max:200,defaultValue:16,displayStepper:true},bottom:{type:ControlType.Number,title:"Bottom",min:0,max:200,defaultValue:16,displayStepper:true},useGradient:{type:ControlType.Boolean,title:"Use Gradient",enabledTitle:"Gradient",disabledTitle:"Solid",defaultValue:false},backgroundColor:{type:ControlType.Color,title:"Background",defaultValue:"#ffffff",hidden:({useGradient})=>!!useGradient},gradient:{type:ControlType.String,title:"Gradient CSS",defaultValue:"linear-gradient(135deg, #FFFFFF 0%, #EEEEEE 100%)",hidden:({useGradient})=>!useGradient},children:{type:ControlType.ComponentInstance,title:"Content"},hAlign:{type:ControlType.Enum,title:"Horizontal",options:["Left","Center","Right"],optionTitles:["Left","Center","Right"],defaultValue:"Center"},vAlign:{type:ControlType.Enum,title:"Vertical",options:["Top","Center","Bottom"],optionTitles:["Top","Center","Bottom"],defaultValue:"Center"}});
export const __FramerMetadata__ = {"exports":{"default":{"type":"reactComponent","name":"Pixel_Background","slots":[],"annotations":{"framerContractVersion":"1"}},"__FramerMetadata__":{"type":"variable"}}}
//# sourceMappingURL=./Pixel_background.map